AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Style/SingleLineBlockParams:
    Enabled: false

Style/ClassVars:
    Enabled: false

Style/CaseEquality:
    Enabled: false

Style/AutoResourceCleanup:
    Enabled: true

Style/AutoResourceCleanup:
    Enabled: true

Style/CollectionMethods:
    Enabled: true

Style/Encoding:
    Enabled: true

Style/StringMethods:
    Enabled: true

Style/SymbolArray:
    Enabled: true
